export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCESS = 'GET_PRODUCTS_SUCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCESS = 'ADD_PRODUCT_SUCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCESS = 'DELETE_PRODUCT_SUCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
